---
chunk_id: discourse_topic_171141_post_114_04
source_url: https://discourse.onlinedegree.iitm.ac.in/t/171141/114
source_title: Tds-official-Project1-discrepencies
content_type: discourse
tokens: 196
username: 22f3000819
post_number: 114
topic_id: 171141
---

 expected functionality of a particular module or file within the project." alt="image" data-base62-sha1="eQVQww2TLZd4V84EezSUFxCArFA" width="302" height="252">image302×252 3.45 KB

---

I think it would be better to enclose each of these function calls in their own try-except blocks. This screenshot is taken from the datagen.py file sent in yesterday’s results mail.

So, will it be possible to re-evaluate my task A1, A8, A9 and A10? At least A9 and A10 did not even get the files to work on as they weren’t even created due to insufficient error handling in datagen.py .

Also, can you help me to identify the cause of even the Pillow default font not being available? I don’t understand how a font not being available could be caused by my code.

Thank you
