---
chunk_id: discourse_topic_164277_post_500_00
source_url: https://discourse.onlinedegree.iitm.ac.in/t/164277/500
source_title: Project 1 - LLM-based Automation Agent - Discussion Thread [TDS Jan 2025]
content_type: discourse
tokens: 110
username: 23f2001286
post_number: 500
topic_id: 164277
---

## Post #500 by 23f2001286

**Direct Link**: [Post #500](https://discourse.onlinedegree.iitm.ac.in/t/164277/500)

sir I am noticing a pattern, that when I am running the datagen first. And then using the evaluate.py, then I am getting the A2 right.

But running the evaluation.py for the 2nd time cause the A2 to fail…

Probabbly Because the file in the data folder gets upated should I worry for that…
